require 'opal'
require 'opal-phaser'

require_relative 'constants'
require_relative 'story_slides'
require_relative 'background'
require_relative 'obstacles'
require_relative 'ground'
require_relative 'text_instructions'
require_relative 'score'
require_relative 'fluttershy'
require_relative 'keys'
require_relative 'flutterjump'